[package]
name = "dedicated-server-availability-watcher"
description = "Check and notify about dedicated servers availability"
version = "0.1.0"
edition = "2021"

# TODO: reduce dependencies
[dependencies]
anyhow = "1.0.68"
clap = { version = "4.0.29", features = ["derive", "cargo"] }
colored = "2.0.0"
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"
thiserror = "1.0.38"
